[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'ffmpeg']

[phases.install]
cmds = ['python -m pip install --upgrade pip', 'python -m pip install -r requirements.txt']

[phases.build]
cmds = ['echo "Build phase complete"']

[start]
cmd = 'gunicorn --bind 0.0.0.0:$PORT app:app --timeout 300 --workers 1'